create index if not exists idx_students_created_at on public.students(created_at desc);
create index if not exists idx_student_pdfs_student_created on public.student_pdfs(student_id, created_at desc);
create index if not exists idx_sources_owner_created on public.sources(owner_id, created_at desc);
create index if not exists idx_sources_owner_status on public.sources(owner_id, status);
create index if not exists idx_source_contents_source on public.source_contents(source_id);
create index if not exists idx_source_chunks_source_chunk on public.source_chunks(source_id, chunk_index);
create index if not exists idx_flashcard_sets_owner_created on public.flashcard_sets(owner_id, created_at desc);
create index if not exists idx_flashcards_set on public.flashcards(set_id);
create index if not exists idx_flashcard_reviews_user_time on public.flashcard_reviews(user_id, reviewed_at desc);
create index if not exists idx_flashcard_progress_user on public.flashcard_progress(user_id);
create index if not exists idx_sections_source on public.sections(source_id);
create index if not exists idx_section_days_user_date on public.section_study_days(user_id, study_date desc);
create index if not exists idx_concept_maps_owner_created on public.concept_maps(owner_id, created_at desc);
create index if not exists idx_nodes_map on public.concept_map_nodes(map_id);
create index if not exists idx_edges_map on public.concept_map_edges(map_id);
create index if not exists idx_notebook_sessions_owner_created on public.notebook_sessions(owner_id, created_at desc);
create index if not exists idx_notebook_outputs_owner_created on public.notebook_outputs(owner_id, created_at desc);
create index if not exists idx_notebook_outputs_payload_gin on public.notebook_outputs using gin (payload);
create index if not exists idx_presentations_owner_created on public.presentations(owner_id, created_at desc);
create index if not exists idx_presentation_slides_pres_idx on public.presentation_slides(presentation_id, slide_index);
create index if not exists idx_quizzes_owner_created on public.quizzes(owner_id, created_at desc);
create index if not exists idx_quiz_questions_quiz on public.quiz_questions(quiz_id);
create index if not exists idx_quiz_attempts_user_time on public.quiz_attempts(user_id, started_at desc);
create index if not exists idx_grades_owner_recorded on public.grades(owner_id, recorded_at desc);
create index if not exists idx_grade_sim_owner_created on public.grade_simulations(owner_id, created_at desc);
create index if not exists idx_academic_ai_owner_created on public.academic_ai_outputs(owner_id, created_at desc);
create index if not exists idx_academic_ai_payload_gin on public.academic_ai_outputs using gin (payload);
create index if not exists idx_tasks_owner_created on public.tasks(owner_id, created_at desc);
create index if not exists idx_chat_rooms_owner on public.chat_rooms(owner_id);
create index if not exists idx_chat_members_user_room on public.chat_members(user_id, room_id);
create index if not exists idx_chat_messages_room_created on public.chat_messages(room_id, created_at desc);
create index if not exists idx_tutor_conv_owner_created on public.tutor_conversations(owner_id, created_at desc);
create index if not exists idx_tutor_messages_conversation_created on public.tutor_messages(conversation_id, created_at desc);
create index if not exists idx_source_embeddings_owner on public.source_embeddings(owner_id, created_at desc);
create index if not exists idx_source_embeddings_source on public.source_embeddings(source_id);
create index if not exists idx_source_embeddings_vector on public.source_embeddings using ivfflat (embedding vector_cosine_ops) with (lists = 100);
create index if not exists idx_teacher_classes_teacher_created on public.teacher_classes(teacher_id, created_at desc);
create index if not exists idx_teacher_classes_code on public.teacher_classes(code);
create index if not exists idx_class_enrollments_student on public.class_enrollments(student_id, class_id);
create index if not exists idx_class_materials_class_created on public.class_materials(class_id, created_at desc);
create index if not exists idx_teacher_assignments_class_due on public.teacher_assignments(class_id, due_at);
create index if not exists idx_teacher_assignments_teacher_created on public.teacher_assignments(teacher_id, created_at desc);
create index if not exists idx_assignment_submissions_assignment on public.assignment_submissions(assignment_id, created_at desc);
create index if not exists idx_assignment_submissions_student on public.assignment_submissions(student_id, created_at desc);
create index if not exists idx_teacher_announcements_class_created on public.teacher_announcements(class_id, created_at desc);
create index if not exists idx_teacher_grades_class_student on public.teacher_grades(class_id, student_id, created_at desc);
create index if not exists idx_teacher_generated_quizzes_class_created on public.teacher_generated_quizzes(class_id, created_at desc);
create index if not exists idx_lms_courses_owner_created on public.lms_courses(owner_teacher_id, created_at desc);
create index if not exists idx_lms_courses_code on public.lms_courses(code);
create index if not exists idx_lms_sections_course on public.lms_course_sections(course_id, created_at desc);
create index if not exists idx_lms_enrollments_course_user on public.lms_enrollments(course_id, user_id);
create index if not exists idx_lms_enrollments_user_course on public.lms_enrollments(user_id, course_id);
create index if not exists idx_lms_modules_course_position on public.lms_modules(course_id, position);
create index if not exists idx_lms_pages_course_updated on public.lms_pages(course_id, updated_at desc);
create index if not exists idx_lms_files_course_created on public.lms_files(course_id, created_at desc);
create index if not exists idx_lms_assignments_course_due on public.lms_assignments(course_id, due_at);
create index if not exists idx_lms_quizzes_course_created on public.lms_quizzes(course_id, created_at desc);
create index if not exists idx_lms_quiz_attempts_quiz_student on public.lms_quiz_attempts(quiz_id, student_id, started_at desc);
create index if not exists idx_lms_quiz_attempts_student_started on public.lms_quiz_attempts(student_id, started_at desc);
create index if not exists idx_lms_submissions_assignment_student on public.lms_submissions(assignment_id, student_id, submitted_at desc);
create index if not exists idx_lms_submissions_student_created on public.lms_submissions(student_id, created_at desc);
create index if not exists idx_lms_rubric_sets_assignment on public.lms_rubric_sets(assignment_id, created_at desc);
create index if not exists idx_lms_rubric_scores_submission on public.lms_rubric_scores(submission_id, created_at desc);
create index if not exists idx_lms_module_items_module_pos on public.lms_module_items(module_id, position);
create index if not exists idx_lms_discussions_course_created on public.lms_discussions(course_id, created_at desc);
create index if not exists idx_lms_discussion_replies_discussion on public.lms_discussion_replies(discussion_id, created_at);
create index if not exists idx_lms_inbox_threads_course_updated on public.lms_inbox_threads(course_id, updated_at desc);
create index if not exists idx_lms_inbox_participants_user on public.lms_inbox_participants(user_id, thread_id);
create index if not exists idx_lms_inbox_messages_thread_created on public.lms_inbox_messages(thread_id, created_at desc);
create index if not exists idx_lms_calendar_owner_start on public.lms_calendar_events(owner_id, start_at);
create index if not exists idx_lms_notifications_user_created on public.lms_notifications(user_id, created_at desc);
create index if not exists idx_lms_notifications_user_read on public.lms_notifications(user_id, read_at);
create index if not exists idx_lms_todo_user_due on public.lms_todo_items(user_id, due_at);
create index if not exists idx_lms_analytics_course_created on public.lms_analytics_events(course_id, created_at desc);
create index if not exists idx_lms_analytics_user_created on public.lms_analytics_events(user_id, created_at desc);
create index if not exists idx_lms_attendance_course_date on public.lms_attendance(course_id, attendance_date desc);
create index if not exists idx_lms_attendance_student_date on public.lms_attendance(student_id, attendance_date desc);
create index if not exists idx_lms_role_bindings_user_scope on public.lms_role_bindings(user_id, scope_type, scope_id);
create index if not exists idx_lms_permission_overrides_scope on public.lms_permission_overrides(scope_type, scope_id, role);
create index if not exists idx_lms_audit_actor_created on public.lms_audit_events(actor_id, created_at desc);
create index if not exists idx_lms_audit_entity on public.lms_audit_events(entity_type, entity_id, created_at desc);

create index if not exists idx_sources_title_fts on public.sources using gin (to_tsvector('simple', coalesce(title, '')));
create index if not exists idx_source_contents_text_fts on public.source_contents using gin (to_tsvector('english', coalesce(cleaned_text, '')));
