create table if not exists public.students (
  id text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.student_pdfs (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete cascade,
  name text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.concept_maps (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete cascade,
  source_name text not null,
  title text not null,
  map_json text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notebook_outputs (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete cascade,
  source_names text not null,
  output_type text not null,
  output_json text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_student_pdfs_student_id on public.student_pdfs(student_id);
create index if not exists idx_concept_maps_student_id on public.concept_maps(student_id);
create index if not exists idx_notebook_outputs_student_id on public.notebook_outputs(student_id);
