create index if not exists idx_sources_owner_created on public.sources(owner_id, created_at desc);
create index if not exists idx_sources_owner_status on public.sources(owner_id, status);
create index if not exists idx_source_contents_source on public.source_contents(source_id);
create index if not exists idx_source_chunks_source_chunk on public.source_chunks(source_id, chunk_index);
create index if not exists idx_flashcard_sets_owner_created on public.flashcard_sets(owner_id, created_at desc);
create index if not exists idx_flashcards_set on public.flashcards(set_id);
create index if not exists idx_flashcard_reviews_user_time on public.flashcard_reviews(user_id, reviewed_at desc);
create index if not exists idx_flashcard_progress_user on public.flashcard_progress(user_id);
create index if not exists idx_sections_source on public.sections(source_id);
create index if not exists idx_section_days_user_date on public.section_study_days(user_id, study_date desc);
create index if not exists idx_concept_maps_owner_created on public.concept_maps(owner_id, created_at desc);
create index if not exists idx_nodes_map on public.concept_map_nodes(map_id);
create index if not exists idx_edges_map on public.concept_map_edges(map_id);
create index if not exists idx_notebook_sessions_owner_created on public.notebook_sessions(owner_id, created_at desc);
create index if not exists idx_notebook_outputs_owner_created on public.notebook_outputs(owner_id, created_at desc);
create index if not exists idx_notebook_outputs_payload_gin on public.notebook_outputs using gin (payload);
create index if not exists idx_presentations_owner_created on public.presentations(owner_id, created_at desc);
create index if not exists idx_presentation_slides_pres_idx on public.presentation_slides(presentation_id, slide_index);
create index if not exists idx_quizzes_owner_created on public.quizzes(owner_id, created_at desc);
create index if not exists idx_quiz_questions_quiz on public.quiz_questions(quiz_id);
create index if not exists idx_quiz_attempts_user_time on public.quiz_attempts(user_id, started_at desc);
create index if not exists idx_grades_owner_recorded on public.grades(owner_id, recorded_at desc);
create index if not exists idx_grade_sim_owner_created on public.grade_simulations(owner_id, created_at desc);
create index if not exists idx_academic_ai_owner_created on public.academic_ai_outputs(owner_id, created_at desc);
create index if not exists idx_academic_ai_payload_gin on public.academic_ai_outputs using gin (payload);
create index if not exists idx_tasks_owner_created on public.tasks(owner_id, created_at desc);
create index if not exists idx_chat_rooms_owner on public.chat_rooms(owner_id);
create index if not exists idx_chat_members_user_room on public.chat_members(user_id, room_id);
create index if not exists idx_chat_messages_room_created on public.chat_messages(room_id, created_at desc);
create index if not exists idx_tutor_conv_owner_created on public.tutor_conversations(owner_id, created_at desc);
create index if not exists idx_tutor_messages_conversation_created on public.tutor_messages(conversation_id, created_at desc);
create index if not exists idx_teacher_classes_teacher_created on public.teacher_classes(teacher_id, created_at desc);
create index if not exists idx_teacher_classes_code on public.teacher_classes(code);
create index if not exists idx_class_enrollments_student on public.class_enrollments(student_id, class_id);
create index if not exists idx_class_materials_class_created on public.class_materials(class_id, created_at desc);
create index if not exists idx_teacher_assignments_class_due on public.teacher_assignments(class_id, due_at);
create index if not exists idx_teacher_assignments_teacher_created on public.teacher_assignments(teacher_id, created_at desc);
create index if not exists idx_assignment_submissions_assignment on public.assignment_submissions(assignment_id, created_at desc);
create index if not exists idx_assignment_submissions_student on public.assignment_submissions(student_id, created_at desc);
create index if not exists idx_teacher_announcements_class_created on public.teacher_announcements(class_id, created_at desc);
create index if not exists idx_teacher_grades_class_student on public.teacher_grades(class_id, student_id, created_at desc);
create index if not exists idx_teacher_generated_quizzes_class_created on public.teacher_generated_quizzes(class_id, created_at desc);

create index if not exists idx_sources_title_fts on public.sources using gin (to_tsvector('simple', coalesce(title, '')));
create index if not exists idx_source_contents_text_fts on public.source_contents using gin (to_tsvector('english', coalesce(cleaned_text, '')));
